# Generated by Django 5.0.7 on 2024-07-11 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='image',
        ),
        migrations.AlterField(
            model_name='categorymodel',
            name='created_at',
            field=models.DateTimeField(verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='categorymodel',
            name='update_at',
            field=models.DateTimeField(verbose_name='update'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='created_at',
            field=models.DateTimeField(verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='status',
            field=models.IntegerField(choices=[(1, 'published'), (2, 'draft')], default=1, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='update_at',
            field=models.DateTimeField(verbose_name='update'),
        ),
    ]
