# Generated by Django 5.0.7 on 2024-07-11 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_categorymodel_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='status',
        ),
    ]
