# Generated by Django 5.0.7 on 2024-07-11 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_remove_productmodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='image',
            field=models.ImageField(default='shop/default.jpg/', upload_to='shop/', verbose_name='image'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='status',
            field=models.IntegerField(choices=[(1, 'published'), (2, 'draft')], default=1, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='update_at',
            field=models.DateTimeField(auto_now=True, verbose_name='update'),
        ),
    ]
