# Generated by Django 5.0.7 on 2024-07-11 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_commentmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentmodel',
            name='update_at',
        ),
    ]
