# Generated by Django 5.0.7 on 2024-07-12 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('shop', '0011_wishlistmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CartItem',
            new_name='CartItemModel',
        ),
    ]
